import type { PickupRequest } from '../../shared/schemas/pickup.schema';
import { getOperationalDate } from '../../shared/utils/date';

const today = getOperationalDate();

export const DEMO_TICKETS: PickupRequest[] = [
  {
    id: 'ticket-demo-1',
    ticketCode: 'JSP-20260613-0001',
    source: 'WHATSAPP',
    customerId: 'customer-1',
    customerPhoneNumber: '628123456789',
    customerName: 'Ibu Sari',
    district: 'PALETEANG',
    villageId: 'mamminasae',
    addressText: 'Dekat Masjid Nurul Huda, Paleteang',
    location: { lat: -3.793, lng: 119.652 },
    serviceType: 'ONE_TRIP_TRICYCLE',
    volumeLevel: 'LARGE',
    tricycleLoadEstimate: 'THREE_QUARTERS',
    wasteDescription: 'Tumpukan kardus dan kantong rumah tangga.',
    photoUrls: [],
    status: 'NEEDS_OPERATOR_REVIEW',
    aiAnalysis: {
      sourceMessageIds: ['demo-message-1'],
      intent: 'PICKUP_REQUEST',
      detectedDistrict: 'PALETEANG',
      addressCompleteness: 'COMPLETE',
      photoQuality: 'CLEAR',
      wasteVisible: true,
      detectedWasteTypes: ['CARDBOARD', 'HOUSEHOLD_MIXED'],
      volumeLevel: 'LARGE',
      tricycleLoadEstimate: 'THREE_QUARTERS',
      recommendedServiceType: 'ONE_TRIP_TRICYCLE',
      needsOperatorReview: true,
      needsMoreInfo: false,
      missingFields: [],
      safetyFlags: ['NONE'],
      customerReply: 'Data sudah kami terima.',
      operatorSummary: 'Volume cukup besar, kemungkinan satu kali jalan.',
      confidence: 0.88,
    },
    createdAt: `${today}T01:15:00.000Z`,
    updatedAt: `${today}T01:15:00.000Z`,
  },
  {
    id: 'ticket-demo-2',
    ticketCode: 'JSP-20260613-0002',
    source: 'WHATSAPP',
    customerId: 'customer-2',
    customerPhoneNumber: '628987654321',
    customerName: 'Pak Rahman',
    district: 'WATANG_SAWITTO',
    villageId: 'maccorawalie',
    addressText: 'Jalan Jenderal Sudirman',
    serviceType: 'REGULAR_HOUSEHOLD_PICKUP',
    volumeLevel: 'SMALL',
    tricycleLoadEstimate: 'QUARTER',
    wasteDescription: 'Tiga kantong sampah rumah tangga.',
    photoUrls: [],
    status: 'NEEDS_INFO',
    createdAt: `${today}T02:30:00.000Z`,
    updatedAt: `${today}T02:30:00.000Z`,
  },
  {
    id: 'ticket-demo-3',
    ticketCode: 'JSP-20260612-0008',
    source: 'ADMIN',
    customerId: 'customer-3',
    customerPhoneNumber: '628111222333',
    customerName: 'Toko Berkah',
    district: 'PALETEANG',
    villageId: 'benteng-sawitto',
    addressText: 'Pasar Paleteang',
    serviceType: 'ONE_TRIP_TRICYCLE',
    volumeLevel: 'MEDIUM',
    tricycleLoadEstimate: 'HALF',
    wasteDescription: 'Kardus toko.',
    photoUrls: [],
    status: 'ASSIGNED',
    scheduledDate: today,
    scheduledTimeWindow: { start: '09:00', end: '12:00' },
    assignedDriverId: 'driver-1',
    assignedDriverName: 'Pak Amir',
    createdAt: `${today}T00:30:00.000Z`,
    updatedAt: `${today}T03:00:00.000Z`,
  },
];
