export const WASTE_ANALYSIS_JSON_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  properties: {
    intent: {
      type: 'string',
      enum: [
        'PICKUP_REQUEST',
        'REGULAR_SUBSCRIPTION_INQUIRY',
        'ASK_PRICE',
        'ASK_AREA',
        'COMPLAINT',
        'OTHER',
      ],
    },
    detectedDistrict: {
      type: 'string',
      enum: ['WATANG_SAWITTO', 'PALETEANG', 'OUT_OF_AREA', 'UNKNOWN'],
    },
    addressCompleteness: {
      type: 'string',
      enum: ['COMPLETE', 'PARTIAL', 'MISSING'],
    },
    photoQuality: {
      type: 'string',
      enum: ['CLEAR', 'PARTIAL', 'BLURRY', 'NO_PHOTO'],
    },
    wasteVisible: { type: 'boolean' },
    detectedWasteTypes: {
      type: 'array',
      minItems: 1,
      items: {
        type: 'string',
        enum: [
          'HOUSEHOLD_MIXED',
          'CARDBOARD',
          'PLASTIC',
          'ORGANIC',
          'GARDEN_WASTE',
          'BULKY_ITEM',
          'GLASS',
          'E_WASTE',
          'HAZARDOUS',
          'UNKNOWN',
        ],
      },
    },
    volumeLevel: {
      type: 'string',
      enum: ['SMALL', 'MEDIUM', 'LARGE', 'OVERSIZED', 'UNKNOWN'],
    },
    tricycleLoadEstimate: {
      type: 'string',
      enum: [
        'NONE',
        'QUARTER',
        'HALF',
        'THREE_QUARTERS',
        'FULL',
        'OVER_CAPACITY',
        'UNKNOWN',
      ],
    },
    recommendedServiceType: {
      type: 'string',
      enum: [
        'REGULAR_HOUSEHOLD_PICKUP',
        'ONE_TRIP_TRICYCLE',
        'NEEDS_OPERATOR_REVIEW',
        'REJECT',
      ],
    },
    needsOperatorReview: { type: 'boolean' },
    needsMoreInfo: { type: 'boolean' },
    missingFields: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'DISTRICT',
          'ADDRESS',
          'LOCATION',
          'PHOTO',
          'WASTE_DESCRIPTION',
        ],
      },
    },
    safetyFlags: {
      type: 'array',
      minItems: 1,
      items: {
        type: 'string',
        enum: [
          'POSSIBLE_MEDICAL_WASTE',
          'POSSIBLE_CHEMICAL',
          'POSSIBLE_B3',
          'SHARP_OBJECTS',
          'CONSTRUCTION_DEBRIS',
          'DEAD_ANIMAL',
          'NONE',
        ],
      },
    },
    customerReply: { type: 'string' },
    operatorSummary: { type: 'string' },
    confidence: { type: 'number', minimum: 0, maximum: 1 },
  },
  required: [
    'intent',
    'detectedDistrict',
    'addressCompleteness',
    'photoQuality',
    'wasteVisible',
    'detectedWasteTypes',
    'volumeLevel',
    'tricycleLoadEstimate',
    'recommendedServiceType',
    'needsOperatorReview',
    'needsMoreInfo',
    'missingFields',
    'safetyFlags',
    'customerReply',
    'operatorSummary',
    'confidence',
  ],
} as const;
